### ISSUE TITLE
docarray support

### ISSUE THREAD

**Issue by hanxiao** [osoken/sqlitecollections#165]
Hi Takeshi, I found this repo very interesting. I'm currently working on sqlite backend for https://github.com/jina-ai/docarray  Would be nice to keep in touch and get your review on it.

I'm also referring https://github.com/RaRe-Technologies/sqlitedict

**Comment by osoken** [comment]
Thank you for your reaching out. Maybe one of my motivation for this personal project, training deep neural network with huge data without using huge memory, would be similar to your goal.
I'll keep an eye on your project and thankfully close this issue.
